<?php
return [
    'welcome' => 'Welcome',
    'login' => 'Login',
    'register' => 'Register',
    'username' => 'Username',
    'password' => 'Password',
    'dashboard' => 'Dashboard',
    'add_income' => 'Add Income',
    'add_expense' => 'Add Expense',
    'total_income' => 'Total Income',
    'total_expense' => 'Total Expense',
    'balance' => 'Balance',
    'logout' => 'Logout',
    'summary_dashboard' => 'summary dashboard',
    'view_records' => 'view records',
    'records' => 'Records',
    'submit' => 'Submit',
    'amount' => 'Amount',
    'category' => 'Category',
    'date' => 'Date',
    'language' => 'Language',
    'select_language' => 'Select Language',
    'add income' => 'Add Income',
    'income_added' => 'Income added successfully!',
    'income_error' => 'Something went wrong, try again!',
    'monthly_chart' => 'Monthly Income vs Expense',
    'income' => 'Income',
    'expense' => 'Expense',
    'budget_exceeded' => 'You have exceeded your monthly budget!',
    'budget_low' => 'Your budget is below 20%!',
    'budget_safe' => 'Your budget is safe!',
    'no_account' => "Don't have an account?",
    'register_here' => 'Register here',
    'period' => 'Period',
    'daily' => 'Daily',
    'weekly' => 'Weekly',
    'monthly' => 'Monthly',
    "footer_rights" => "All Rights Reserved.",
    "footer_designed" => "Designed  by",
    "footer_Phone_number" => "",




];
